### ISSUE TITLE
Compiler crash on invalid syntax (Win 10 64-bit)

### ISSUE THREAD

**Issue by foxbunny** [gkz/LiveScript#932] opened 2016-10-27 15:24 UTC
As tested with lsc 1.5 on Win 10, using Node 4.6 and 6.8, I get compiler crashes on invalid syntax.

If we have `mini.ls` that looks like this:

```
`test`
```

And we execute `lsc -wc mini.ls`, the result is this:

```
C:\Users\hajim\AppData\Roaming\nvm\v4.6.0\node_modules\livescript\lib\command.js:260
            warn(e + '\x07');
                   ^

TypeError: Function.prototype.toString is not generic
    at Function.toString (native)
    at compileScript (C:\Users\hajim\AppData\Roaming\nvm\v4.6.0\node_modules\livescript\lib\command.js:260:20)
    at C:\Users\hajim\AppData\Roaming\nvm\v4.6.0\node_modules\livescript\lib\command.js:152:11
    at C:\Users\hajim\AppData\Roaming\nvm\v4.6.0\node_modules\livescript\lib\command.js:142:7
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

I've also run into several other cases, but unfortunately did not bother to record them.

**Comment by summivox** [comment] 2016-11-14 18:42
dupe of #900 
fixed by #901

**Closed** 2017-05-17 14:11 UTC
Labels: duplicate
