### ISSUE TITLE
Filenames with a dot compile into a file without the .js extension

### ISSUE THREAD

**Issue by cyberco** [gkz/LiveScript#883] opened 2016-04-19 14:03 UTC
Compiling a file with a dot in its name results in a javascript file without the .js extension. E.g.:

`lsc -c foo.bar.ls`

results in:

`foo.bar`

**Comment by vendethiel** [comment] 2016-04-19 14:16
Duplicate of #295.

**Closed by vendethiel** 2016-04-19 14:16 UTC
