### ISSUE TITLE
arbitrary radix literal 0 (e.g. `8~00` ) fails miserably

### ISSUE THREAD

**Issue by summivox** [gkz/LiveScript#920] opened 2016-08-08 20:07 UTC
`8~0` => `0`

`8~00` => `bind$(8, '00')`

`8~01` => `1`

**Comment by pepkin88** [comment] 2016-08-24 14:05
A duplicate of https://github.com/gkz/LiveScript/issues/509

**Closed** 2017-05-17 13:57 UTC
Labels: duplicate
