### ISSUE TITLE
`is` and `isnt` have the wrong precedence

### ISSUE THREAD

**Issue by farzher** [gkz/LiveScript#704] opened 2015-04-08 04:17 UTC
What I mean by this is that `getParam 'name' is 'john'` should compile to `getParam('name') === 'john'` and not `getParam('name' === 'john')`

I know @gkz is aware of this.
Will this not be fixed until livescript 2 because it's a breaking change?
I'm still using a version of LS 1.2 that I forked to fix this issue a while ago.

I have a possible solution to the fact it's a breaking change.
Add a compiler flag to "enable breaking changes"
Maybe there's some other issues that could be cleaned up by that too.

**Comment by vendethiel** [comment] 2015-04-08 07:13
This is a dupe of #204.

> Add a compiler flag to "enable breaking changes"

we don't want our compile flags to change the code output, especially with a change like that.


> Will this not be fixed until livescript 2 because it's a breaking change?

Well, it'd break a ton of code, and it'd be really hard to "fix" it.

**Closed by vendethiel** 2015-04-08 07:13 UTC

**Comment by gkz** [comment] 2015-04-08 07:45
If LS2 happens I'll fix this.
